### ISSUE TITLE
string Title can help you.

### ISSUE THREAD

**Issue by daheige** [edocevol/cogo-job#2]
https://github.com/edocevol/cogo-job/blob/9151d06e5094ef292e36113b256386b1a27608e6/lib/string_utils.go#L5

please use strings.Title func convert str, like this code:
var str = "heige"
log.Println(strings.Title(str)) //2019/06/01 22:18:15 HEIGE

**Comment by edocevol** [comment]
![image](https://user-images.githubusercontent.com/9777120/58774322-72bc4900-85f3-11e9-9d58-5c1d6e79ab56.png)

![image](https://user-images.githubusercontent.com/9777120/58774338-87004600-85f3-11e9-92c7-cd774898c127.png)

As you see, `title` **Upper** first Letter of your string，but we need a function **lower** our first letter.
