### ISSUE TITLE
Control code logic at specified times，please use done+select+time.After

### ISSUE THREAD

**Issue by daheige** [edocevol/cogo-job#4]
https://github.com/edocevol/cogo-job/blob/9151d06e5094ef292e36113b256386b1a27608e6/gjobs/plugin/Demo/PluginDemoJob.go#L15

please look this code: 
https://github.com/daheige/thinkgo/blob/master/common/common.go#L340

**Comment by edocevol** [comment]
fix in commit/fd571c350279f177bb2dadce922ca2dda914c7ad
